# Generated by Django 5.2.1 on 2025-06-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_case_status_alter_client_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='board',
            field=models.CharField(choices=[('1', 'ადმინისტრაციული'), ('2', 'სამოქალაქო'), ('3', 'ად. სამართალდარღვევა'), ('4', 'წინასასამართო')], default='1', max_length=1),
        ),
    ]
