# Generated by Django 5.1.3 on 2025-07-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_case_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='system_pass',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='system_user',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
